### PR TITLE
Fix ProcState parsing for process names with parantheses

### LINKED ISSUE #81: /proc/<pid>/stat file is incorrectly parsed when comm contains parentheses
I just noticed the following error when running metricbeat 6.0.0-rc1 at ubuntu linux.

`2017/10/30 16:05:31.762957 process_summary.go:79: ERR Unknown state <41> for process with pid 1467                                                                                           `

It looks like ProcState.Get(int) incorrectly assumes a process name can't include ")" and splits the content by ")" character. This results the State being ")" <41> and other entries to be garbled.

```
ubuntu@ip-172-31-17-129:/etc/nginx$ cat /proc/1467/stat                                                                                                                                      
1467 ((sd-pam)) S 1465 1465 1465 0 -1 1077936448 23 0 0 0 0 0 0 0 20 0 1 0 3448 63012864 566 18446744073709551615 1 1 0 0 0 0 0 4096 0 0 0 0 17 1 0 0 0 0 0 0 0 0 0 0 0 0 0                  
```

EDIT: not ProcList but ProcState

### PR DESCRIPTION
**Pull request by andrewkroh**
- Refactor the ProcState code that parses /proc/[PID]/stat to allow any characters between the opening and closing parentheses of the comm field.
- This also improves the error handling in ProcState.Get. Previously errors from `strconv.Atio` were not checked.
- Improved the test for ProcState to validate all fields.
- Fix bug in test code that generates fake /proc/pid/stat data. It skipped "19" causing an off by one issue.

Fixes #81

### CODE REVIEW

**Comment by andrewkroh** [comment]
@immon I opened a PR for this myself because I wanted to do some additional refactoring to the code to improve error handling.

File: sigar_linux_common.go [hunk 1]
```diff
@@ -181,44 +180,58 @@ func (self *ProcList) Get() error {
...
-
-	name := strings.SplitAfterN(pidAndName, " ", 2)[1]
-	if name[0] == '(' && name[len(name)-1] == ')' {
-		self.Name = name[1 : len(name)-1] // strip ()'s
-	} else {
-		return errors.New(fmt.Sprintf("Malformed process stats for pid %d", pid))
+	// Extract the comm value with is surrounded by parentheses.
+	lIdx := bytes.Index(data, []byte("("))
+	rIdx := bytes.LastIndex(data, []byte(")"))
+	if lIdx < 0 || rIdx < 0 {
```
Comment (adriansr) [inline sigar_linux_common.go]: Nit: Should return an error also when `lIdx >= rIdx || rIdx + 2 >= len(data)`
to avoid crashing below.

**Comment by andrewkroh** [comment]
This has been updated based on the review feedback.
