### PR TITLE
fix linux readFile for long lines

### LINKED ISSUE #166: panic on FileSystemList.Get
```
goroutine 83 [running]:
github.com/elastic/gosigar.(*FileSystemList).Get.func1({0xc0019b8ab0, 0xc000ae9000})
	github.com/elastic/gosigar/external/com_github_elastic_gosigar/sigar_linux_common.go:113 +0x1b0
github.com/elastic/gosigar.readFile({0x4e8860e, 0x200000003}, 0xc000ac7440)
	github.com/elastic/gosigar/external/com_github_elastic_gosigar/sigar_linux_common.go:386 +0x208
github.com/elastic/gosigar.(*FileSystemList).Get(0xc000ac7508)
	github.com/elastic/gosigar/external/com_github_elastic_gosigar/sigar_linux_common.go:106 +0x8f
github.com/cockroachdb/cockroach/pkg/storage.getFileSystemProperties({0x6355138, 0xc000828e40}, {0xc00095f2f0, 0x21})
	github.com/cockroachdb/cockroach/pkg/storage/store_properties.go:60 +0x1d4
github.com/cockroachdb/cockroach/pkg/storage.computeStoreProperties({0x6355138, 0xc000828e40}, {0xc00095f2f0, 0x3d}, 0x47, 0x59)
```
If an entry in the mount table file doesn't have the options defined, then FileSystemList.Get can panic as shown.

### PR DESCRIPTION
**Pull request by ap-wtioit**
when reading /etc/mtab with long lines (>4096 bytes) reader.ReadLine() return isPrefix as true and we append the next returned line to the buffer before passing it to the handler

fixes #166 

Info @wt-io-it

### CODE REVIEW

**Comment by ap-wtioit** [comment]
The CLA should be signed by now.

File: sigar_linux_common.go [hunk 1]
```diff
@@ -378,15 +378,33 @@ func readFile(file string, handler func(string) bool) error {
 	}
 
 	reader := bufio.NewReader(bytes.NewBuffer(contents))
+	read_line_bytes := new(bytes.Buffer)
+	break_after_line := false
 
 	for {
-		line, _, err := reader.ReadLine()
+		line, prefix, err := reader.ReadLine();
```
Comment (jsoriano) [inline sigar_linux_common.go:385]: Should we use [`reader.ReadString('\n')`](https://pkg.go.dev/bufio#Reader.ReadString) instead? We are keeping the whole line in the buffer in any case.
```suggestion
		line, err := reader.ReadString('\n');
```

Or we could maybe use a [bufio.Scanner](https://pkg.go.dev/bufio#Scanner) too.

**Review by jsoriano — COMMENTED** [review]
Thanks for the fix!

Do you have a sample file that reproduces the issue? Would it be possible to add a test case with it?

**Comment by ap-wtioit** [comment]
> Do you have a sample file that reproduces the issue? Would it be possible to add a test case with it?

I expected the graylog sidecar issue to be linked here as well (did not work as expected by me):
https://github.com/Graylog2/collector-sidecar/issues/503

longest line 4178 bytes from our server were i experienced the crashes (before deploying a patched version):
```
overlay /var/lib/docker/overlay2/229ea374b94e0a60368c0759cc104aa3ef44e7bd46e8e389603307673aab34e7/merged overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/25NOBV3WHXG5P3GRO2FRUCWAB3:/var/lib/docker/overlay2/l/NORNMK2W42ELHAA4GJWQX5ZOAW:/var/lib/docker/overlay2/l/RDVR4KEE5JQPI5SDRG333UL7RR:/var/lib/docker/overlay2/l/NDA6EGGA5TVHNZYRLSNACMCQWF:/var/lib/docker/overlay2/l/PSHEG744SP6T5QTAYIBKOHQRTF:/var/lib/docker/overlay2/l/CVJ6EWWFZZB4XNNCTTX2OWOKC7:/var/lib/docker/overlay2/l/OYEE2F2W4IA5RFZE6ZBTHJIUSH:/var/lib/docker/overlay2/l/ZRFGD5OZAXDXEACSMEYWGGSBX7:/var/lib/docker/overlay2/l/CILYIYAPTFNWP7UM7S55KQSI4D:/var/lib/docker/overlay2/l/F4PHFL4L2NAF5GJSJIGQPERKPU:/var/lib/docker/overlay2/l/5R62UHZSGCI2AH7SYFUHVMH56E:/var/lib/docker/overlay2/l/2SENKE2UI73NBAGTGIVH6K3O2A:/var/lib/docker/overlay2/l/DWRXBEGY7U3IIIBVEA6V2AKRBJ:/var/lib/docker/overlay2/l/3GUSTJRGFDDYXLT7V44I6YB3XN:/var/lib/docker/overlay2/l/DEC4B5I67LMALKVPQJAFP5HX46:/var/lib/docker/overlay2/l/ZI5YOAKJUTPBKKOMMTWKITYIXS:/var/lib/docker/overlay2/l/RKWKKH46TJP7S6ZERYR5SPS73N:/var/lib/docker/overlay2/l/LQTPCWBTTXHTHKNCQZF2E2D6AP:/var/lib/docker/overlay2/l/HUNN3R34OVJSNKILBJSMTJTIFO:/var/lib/docker/overlay2/l/S6DGOW3IPS2PT463PG7SYRMUJX:/var/lib/docker/overlay2/l/GKZU26J5SSSQH2RBIMKYUDUNWQ:/var/lib/docker/overlay2/l/SPS2VYCUOWEKCA47Q2FL3T3ZVO:/var/lib/docker/overlay2/l/DJ7CFAJ64XB7AFGAM5UZ3MEOHT:/var/lib/docker/overlay2/l/MJOQ7IFA5JLZ4APQHPRA2GFIKF:/var/lib/docker/overlay2/l/DVAUELMLR5VFOLXLCG4RHVJJH4:/var/lib/docker/overlay2/l/DDV4OD36D4CACTBTVXQ7CQVJTK:/var/lib/docker/overlay2/l/TQSEOKAR5Q4QJI52HJH6TWSENX:/var/lib/docker/overlay2/l/ZJPLLJWA2EDO2QFO6JL5YU5NXC:/var/lib/docker/overlay2/l/NW7MD4MUYBUC27L6XYJTKELXZU:/var/lib/docker/overlay2/l/HF3FA5NGW27JT43D44L4UFWSUS:/var/lib/docker/overlay2/l/MG27ZBUPW3NNRRM4TPE672DPKZ:/var/lib/docker/overlay2/l/IBM7RSWRDIZJPZNAOOW6H3SQUW:/var/lib/docker/overlay2/l/GJI7YYX4T3YCSS35JXQVOLMUPU:/var/lib/docker/overlay2/l/POIXRSHOGGH5SRY6IKBSO7WM6E:/var/lib/docker/overlay2/l/C3HJJ3QW33WNHC33X5VFLUT3DR:/var/lib/docker/overlay2/l/CZNUABCWBZ6T6Z636WZUKBJY3L:/var/lib/docker/overlay2/l/Z2KSHZNRNQ4HUHLXOA4ZBE2P3E:/var/lib/docker/overlay2/l/SJTVBG2UJSGT23AVCSDVR4PNVL:/var/lib/docker/overlay2/l/M7T7PG36WVHPGA5J5QFK6E3Z3T:/var/lib/docker/overlay2/l/3K52OVGIRBUIUOQ7A6XKE3CI7Q:/var/lib/docker/overlay2/l/NPAO3V2FJSNSOIR5IJYRXSJUN2:/var/lib/docker/overlay2/l/MJEUBSKJ3EIEXKI63O23MVJP6L:/var/lib/docker/overlay2/l/KI4KHMEL5YIOHU6M5HJOOP7SOA:/var/lib/docker/overlay2/l/OJ2AAUKW7A27XRU3A6JLFSXPED:/var/lib/docker/overlay2/l/JMSLHEDCQMFBEPIPZGKKPUL2GZ:/var/lib/docker/overlay2/l/63VRX6JDKMNOBZTXFFXGTWLHH4:/var/lib/docker/overlay2/l/WATKHFOLY7ATZ6OSPN63M4SMTN:/var/lib/docker/overlay2/l/2OGULZVZAUODJXF3ZKMTMIRYWC:/var/lib/docker/overlay2/l/2NZZ4KSCVJKL2GCIHHXWPYY3VC:/var/lib/docker/overlay2/l/XOMQEH3JRC4GCBK4ZKEKTISBZV:/var/lib/docker/overlay2/l/SJHHUSXZQ4ZPEZGOFYJ2B7FZHK:/var/lib/docker/overlay2/l/RFETRSPAIPUYYLBY4UWAUEI4WD:/var/lib/docker/overlay2/l/FBF7BNUTJTB4QXRBS4IMF3XTA5:/var/lib/docker/overlay2/l/FEPH4I477I3WOOLYHEFUDJYNYC:/var/lib/docker/overlay2/l/JNZJLFLK6EBJOXBVRY423B5WCW:/var/lib/docker/overlay2/l/QXPFXSXPE3OFAVKJMKEU5OBLGF:/var/lib/docker/overlay2/l/X4LAMESX5ANCAMDB3H5R7EEAGH:/var/lib/docker/overlay2/l/6EM7RPQGAT2QUCPZTOYQL2YA7W:/var/lib/docker/overlay2/l/4YCKFX7RIZSE3X7NR33L2AMXTF:/var/lib/docker/overlay2/l/J4IAXBV7AJD4UXI6E2DKBI5USH:/var/lib/docker/overlay2/l/U4LYG45JPNMLITFZPXRZ4YORNH:/var/lib/docker/overlay2/l/U7YWJNILQ4S3E2GMNKVBDU3HE2:/var/lib/docker/overlay2/l/4Q7NTRFPH6PISJPCGL6MSNKXAB:/var/lib/docker/overlay2/l/S4Q5LW6NPUGGV4PNH7RGIZULDB:/var/lib/docker/overlay2/l/JH4VWREORYUTBEG5OWJGRUTSWZ:/var/lib/docker/overlay2/l/DOSO5DTS2LYOPZNKNNDA6UXJVN:/var/lib/docker/overlay2/l/GI43U22RIMZQU2WCKLILS7VIWU:/var/lib/docker/overlay2/l/ELJJ5B5BDXE2XLUU3SXA7NCFV6:/var/lib/docker/overlay2/l/WSEEZO7VSPHRUZV6ZFJZFI2JOJ:/var/lib/docker/overlay2/l/Q7CHINR3TSEIMNYBXBQEM7GV4X:/var/lib/docker/overlay2/l/OJQEGWPTEYASKMEKOJ2APQ47XI,upperdir=/var/lib/docker/overlay2/229ea374b94e0a60368c0759cc104aa3ef44e7bd46e8e389603307673aab34e7/diff,workdir=/var/lib/docker/overlay2/229ea374b94e0a60368c0759cc104aa3ef44e7bd46e8e389603307673aab34e7/work 0 0
```

If you give me hints how to run the tests i can check if I'm able to add tests (go is not one of my well known languages)

File: sigar_linux_common.go (hunk 1 above)
Comment (ap-wtioit) [reply sigar_linux_common.go:385]: My intention was to not change the used language elements but if you think one of those is better suited, I'll change the patch.

**Comment by jsoriano** [comment]
> If you give me hints how to run the tests i can check if I'm able to add tests (go is not one of my well known languages)

You can run tests with `go test ./...`.

I see there are no tests for `FileSystemList` with custom mtabs, so if you find it complicated to add them maybe it is enough with the manual tests using `examples/df` by now.

**Comment by ap-wtioit** [comment]
> You can run tests with `go test ./...`.

Thanks, now i get a bit more output (was trying `go test` before), will report back if i manage to add a test (based on `func TestLinuxProcState(t *testing.T) {`)

File: sigar_linux_common.go (hunk 1 above)
Comment (jsoriano) [reply sigar_linux_common.go:385]: I think it would be worth to try with some of the alternatives, as the resulting code might be easier to maintain.

For example with `bufio.Scanner` I think this function could be reduced to something like this (not tested):
```go
func readFile(file string, handler func(string) bool) error {
    reader, err := os.Open(file)
    if err != nil {
        return err
    }
    defer reader.Close()

    scanner := bufio.NewScanner(reader)
    for scanner.Scan() {
        if !handler(scanner.Text()) {
            break
        }
    }
    if err := scanner.Error(); err != nil {
        return err // Current code would return nil in this case, but seems wrong :?
    }
    return nil
}
```

**Comment by ap-wtioit** [comment]
Added a test. Output of tests failing for old code of readFile:
```
?       github.com/elastic/gosigar/examples/df  [no test files]
?       github.com/elastic/gosigar/examples/free        [no test files]
?       github.com/elastic/gosigar/examples/ss  [no test files]
?       github.com/elastic/gosigar/examples/ps  [no test files]
?       github.com/elastic/gosigar/fakes        [no test files]
?       github.com/elastic/gosigar/examples/uptime      [no test files]
?       github.com/elastic/gosigar/sys  [no test files]
?       github.com/elastic/gosigar/sys/windows  [no test files]
--- FAIL: TestLinuxFileSystemList (0.00s)
panic: runtime error: index out of range [3] with length 3 [recovered]
        panic: runtime error: index out of range [3] with length 3

goroutine 40 [running]:
testing.tRunner.func1.2({0x5e95e0, 0xc00024aa98})
        /home/redacted/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.linux-amd64/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
        /home/redacted/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.linux-amd64/src/testing/testing.go:1634 +0x377
panic({0x5e95e0?, 0xc00024aa98?})
        /home/redacted/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/elastic/gosigar.(*FileSystemList).Get.func1({0xc000223a40?, 0xc000338000?})
        /home/redacted/Documents/workspace_tools/gosigar/sigar_linux_common.go:116 +0x1ae
github.com/elastic/gosigar.readFile({0xc00023dc20?, 0x1?}, 0xc0000d7c88)
        /home/redacted/Documents/workspace_tools/gosigar/sigar_linux_common.go:389 +0x1de
github.com/elastic/gosigar.(*FileSystemList).Get(0xc0000d7d10)
        /home/redacted/Documents/workspace_tools/gosigar/sigar_linux_common.go:109 +0x86
github.com/elastic/gosigar_test.TestLinuxFileSystemList(0xc0002ec9c0)
        /home/redacted/Documents/workspace_tools/gosigar/sigar_linux_common_test.go:88 +0x18f
testing.tRunner(0xc0002ec9c0, 0x62b708)
        /home/redacted/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.linux-amd64/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
        /home/redacted/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.9.linux-amd64/src/testing/testing.go:1742 +0x390
FAIL    github.com/elastic/gosigar      0.528s
ok      github.com/elastic/gosigar/cgroup       (cached)
ok      github.com/elastic/gosigar/psnotify     (cached)
ok      github.com/elastic/gosigar/sys/linux    (cached)
FAIL
```

File: sigar_linux_common.go (hunk 1 above)
Comment (ap-wtioit) [reply sigar_linux_common.go]: This did work on the first try with the new test, i used it in the latest commit. Thanks for your support.

File: sigar_linux_common_test.go [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+var oldMtabf string
+
+func setUpCommonTest(t testing.TB) {
+	var err error
+	oldMtabf = sigar.Mtabf
+	mtabDir, err = ioutil.TempDir("", "sigarTests")
+	sigar.Mtabf = mtabDir + "/mtab"
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (jsoriano) [inline sigar_linux_common_test.go:23]: You can use `t.TempDir`, that creates a temporary directory that is removed after the test is executed.
And it would be safer to use `filepath.Join()` to build the full path.
```suggestion
	mtabDir, err = t.TempDir()
	sigar.Mtabf = filepath.Join(mtabDir, mtab)
```

File: sigar_linux_common_test.go [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+)
+
+var mtabDir string
+var oldMtabf string
+
+func setUpCommonTest(t testing.TB) {
+	var err error
+	oldMtabf = sigar.Mtabf
+	mtabDir, err = ioutil.TempDir("", "sigarTests")
+	sigar.Mtabf = mtabDir + "/mtab"
```
Comment (jsoriano) [inline sigar_linux_common_test.go:20]: Nit. Not really neccesary, but just in case, you could add a cleanup function to revert to the old value.
```suggestion
	sigar.Mtabf = mtabDir + "/mtab"
	t.Cleanup(func() { sigar.Mtabf = oldMtabf })
```

File: sigar_linux_common_test.go [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+	}
+}
+
+func tearDownCommonTest(t testing.TB) {
+	err := os.RemoveAll(mtabDir)
+	if err != nil {
+		t.Fatal(err)
+	}
+	sigar.Mtabf = oldMtabf
+}
```
Comment (jsoriano) [inline sigar_linux_common_test.go:32]: With the changes proposed above, this teardown wouldn't be needed anymore.

File: sigar_linux_common_test.go [hunk 5]
```diff
@@ -0,0 +1,101 @@
+package gosigar_test
```
Comment (jsoriano) [inline sigar_linux_common_test.go:1]: I think we need the same build tags as in `sigar_linux_common.go`, so this is not executed when running in other operating systems.
```suggestion
package gosigar_test

//go:build freebsd || linux
// +build freebsd linux
```

**Review by jsoriano — COMMENTED** [review]
Thanks for adding the test :+1:

Code looks good to me overall, added a couple of suggestions for the test setup and cleanup.

File: sigar_linux_common_test.go (hunk 5 above)
Comment (ap-wtioit) [reply sigar_linux_common_test.go:4]: i added only linux (the test does not test the freebsd branch, i have no freebsd to verfiy mtab there)

File: sigar_linux_common_test.go [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+		"portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0",
+		"gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0",
+		"/dev/loop75 /snap/discord/225 squashfs ro,nodev,relatime,errors=continue,threads=single 0 0",
+	}
+
+	expected_list := []sigar.FileSystem{}
```
Comment (jsoriano) [inline sigar_linux_common_test.go:57]: Nit. Code conventions.
```suggestion
	expectedList := []sigar.FileSystem{}
```

File: sigar_linux_common_test.go [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+	"testing"
+
+	sigar "github.com/elastic/gosigar"
+	"github.com/stretchr/testify/assert"
+)
+
+func setUpCommonTest(t testing.TB) {
+	oldMtabf := sigar.Mtabf
+	mtabDir := t.TempDir()
+	sigar.Mtabf = filepath.Join(mtabDir, "mtab")
```
Comment (jsoriano) [inline sigar_linux_common_test.go:19]: Nit. Variable not needed.
```suggestion
	sigar.Mtabf = filepath.Join(t.TempDir(), "mtab")
```

**Review by jsoriano — APPROVED** [review]

**Comment by ap-wtioit** [comment]
updated for the 2 nits (too much python on my side for the last years)

**Review by jsoriano — APPROVED** [review]
